"""
Django settings for GSE_Backend project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
import pusher
from core.ParsingManager.ParsingHelper import ParsingHelper

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%zpl)6@v8=g+)&%#s((wud1uhv$0h^tw$qsz=+2x&#b(cs-uzs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    "rest_framework_api_key",
    'api',
    'core',
    'analytics',
    'payment',
    'api_vendor',
    "api_ghg",
    'communication',
    'api_auth',
    'corsheaders',
]
AUTH_USER_MODEL = 'api_auth.User'
MIDDLEWARE = [
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.db_router.RouterMiddleware.RouterMiddleware',
    'django_referrer_policy.middleware.ReferrerPolicyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django_permissions_policy.PermissionsPolicyMiddleware',
]
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')

# RFERRER and PERMISSIONS settings

REFERRER_POLICY='same-origin'

PERMISSIONS_POLICY = {
    "accelerometer": [],
    "ambient-light-sensor": [],
    "autoplay": ["self", "https://archive.org"],
    "camera": [],
    "display-capture": [],
    "document-domain": [],
    "encrypted-media": [],
    "fullscreen": [],
    "geolocation": [],
    "gyroscope": [],
    "interest-cohort": [],
    "magnetometer": [],
    "microphone": [],
    "midi": [],
    "payment": [],
    "usb": [],
}


# ADMINS settings to allow error report emails for 500
# TODO:Change the email in production from .com to services
ADMINS = [('Ana Z', 'azakharova@skyit.services'), ('Slavi Paskalev', 'sppaskal@skyit.com'),
          ('Admin account', 'errors@skyit.services'), ('Anshul Dubey', 'adubey@skyit.com')]
MANAGERS = ADMINS

AUKAI_SUPPORT_EMAIL = "aukai-support@skyit.services"
ORION_SUPPORT_EMAIL = "orion-support@skyit.services"
LOKOMOTIVE_SUPPORT_EMAIL = "lokomotive-support@skyit.services"
ARCHIVE_EMAIL = "aukai-archive@skyit.services"

CORS_ORIGIN_ALLOW_ALL = True
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'default': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(SITE_ROOT, 'logs/logs.log'),
            'maxBytes': 1024*1024*5,
            'backupCount': 5,
            'formatter': 'standard'
        },
        'request_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(SITE_ROOT, 'logs/django-requests.log'),
            'maxBytes': 1024*1024*5,
            'backupCount': 5,
            'formatter': 'standard'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },
    'loggers': {
        '': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['request_handler', 'mail_admins'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'GSE_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GSE_Backend.wsgi.application'

DB_CONN_AGE = 60

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASE_ROUTERS = ['api.db_router.AuthRouter.AuthRouter',
                    'api.db_router.OtherRouter.OtherRouter']


DATABASE_CONSTANTS = {
    'ENGINE': 'django.db.backends.mysql',
    'USER': os.getenv('DB_USERNAME'),
    'PASSWORD': os.getenv('DB_PASSWORD'),
    'HOST': os.getenv('DB_HOST'),  # Can be overridden by actual db_host in env var
    'PORT': '3306',
    'CONN_MAX_AGE': DB_CONN_AGE,
    'OPTIONS': {
        'ssl': {
            'ssl_disabled': True
        }
    }
}

DATABASES = ParsingHelper.parse_database_details_env_var(os.getenv('DATABASE_DETAILS'))

# Number of seconds before token expires - 1year = 31622400
# TOKEN_EXPIRED_AFTER_SECONDS = 31622400
TOKEN_EXPIRED_AFTER_SECONDS = 86400

#Base URL for forgot password API
# TODO: Change to azure env variables that point to production hostings upon release.
FORGOT_PASSWORD_URL = {
    'aukai': 'https://dev-aukai.azurewebsites.net',
    'lokomotive': 'https://lokomotive.azurewebsites.net',
    'orion': 'https://demo-orion.azurewebsites.net'
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


# Password hashing preferences, uses the first hashing algorithm in the list
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]


# Django email services
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.skyit.services'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'noreply@skyit.services'
# #TODO: Get password from environmental variables instead of hardcoding here (not secure)
EMAIL_HOST_PASSWORD = '3Qj_xe2z5Bw#L(j;'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'testorion77@gmail.com'
# #TODO: Get password from environmental variables instead of hardcoding here (not secure)
# EMAIL_HOST_PASSWORD = 't2e0s2t1'
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# SERVER_EMAIL = 'testorion77@gmail.com'


# gse: DefaultEndpointsProtocol=https;AccountName=testorion;AccountKey=899ZQu5DmfswSUwjVHkTG4SDu65uuB929nz17v/Mth7XickfRpydiyaWC02dZzkBx1qlBDriSZo2X1B4dhE4QA==;EndpointSuffix=core.windows.net
# fmt: DefaultEndpointsProtocol=https;AccountName=aukaifmt;AccountKey=ERluQam+4nWHntxH2QgjgHZu1dPwrIoErueA0hrycqI9jLYrOplMYSHuEnvWfrxLvmTVFVReqQ8iOFY5c6oIhA==;EndpointSuffix=core.windows.net
CONNECTION_STRINGS = ParsingHelper.parse_blob_connection_strings_env_var(os.getenv('BLOB_CONNECTION_STRINGS'))

#Azure Cognitive services credentials
ENDPOINT = "https://skyit-form-recognizer.cognitiveservices.azure.com/"
KEY = "9ccca0c86dad4b60a5344845f224d57d"

sentry_sdk.init(
    dsn="https://137a7ed6035a4910b4a5a1eda8300d78@o587099.ingest.sentry.io/5738507",
    integrations=[DjangoIntegration()],
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)

# TODO: Get these values from environment variables
PUSHER_CLIENT = pusher.Pusher(
    app_id="1334339",
    key="135fdf925852f78c4eee",
    secret="b916a862c56a91e01d34",
    encryption_master_key_base64="tc1nJliwW+ZJcbxGX9uSw5uduuCWCn/kdfRjnaC0qmM=",
    cluster="us2",
    ssl=True
)

SERVICE_BUS_LISTEN_TOPIC_CONNECTION_DETAILS = {
    "WestJet": {
        "topic_name": "test-topic",
        "subscription_name": "test-subscription-westjet",
        "primary_key": "wzQ0Hvc9VaIgSduKjv88rbtGp4IFTd6GvLiw334wLBA=",
        "secondary_key": "3+KkhD/Eke2dJBr1JqtLHmuH/WDHdAXcTw9fyRNeM6k=",
        "primary_connection_string": "Endpoint=sb://skyit-dev-service-bus.servicebus.windows.net/;SharedAccessKeyName=test-topic-listen-key;SharedAccessKey=wzQ0Hvc9VaIgSduKjv88rbtGp4IFTd6GvLiw334wLBA=;EntityPath=test-topic",
        "secondary_connection_string": "Endpoint=sb://skyit-dev-service-bus.servicebus.windows.net/;SharedAccessKeyName=test-topic-listen-key;SharedAccessKey=3+KkhD/Eke2dJBr1JqtLHmuH/WDHdAXcTw9fyRNeM6k=;EntityPath=test-topic"
    },
    "FMT": {
        "topic_name": "test-topic",
        "subscription_name": "test-subscription-fmt",
        "primary_key": "wzQ0Hvc9VaIgSduKjv88rbtGp4IFTd6GvLiw334wLBA=",
        "secondary_key": "3+KkhD/Eke2dJBr1JqtLHmuH/WDHdAXcTw9fyRNeM6k=",
        "primary_connection_string": "Endpoint=sb://skyit-dev-service-bus.servicebus.windows.net/;SharedAccessKeyName=test-topic-listen-key;SharedAccessKey=wzQ0Hvc9VaIgSduKjv88rbtGp4IFTd6GvLiw334wLBA=;EntityPath=test-topic",
        "secondary_connection_string": "Endpoint=sb://skyit-dev-service-bus.servicebus.windows.net/;SharedAccessKeyName=test-topic-listen-key;SharedAccessKey=3+KkhD/Eke2dJBr1JqtLHmuH/WDHdAXcTw9fyRNeM6k=;EntityPath=test-topic"
    }
}

# TODO: Extract to environmental variables in azure.
INTERNAL_INTEGRATION_SYSTEM_HEADERS = (
    '{"Authorization":"Api-Key rB5ayDna.So4KYO2pWfmgScQqBeYXTe8wmpfVQI9g"}'
)

VENDOR_SYSTEM_BASE_URL = "https://be-vendor-dev-1.azurewebsites.net/api-client/v1/"
# VENDOR_SYSTEM_BASE_URL = "http://127.0.0.1:8000/api-client/v1/"


MICROSERVICE_SYSTEM_HEADERS = (
    '{"Authorization":"Api-Key rB5ayDna.So4KYO2pWfmgScQqBeYXTe8wmpfVQI9g"}'
)

# MICROSERVICE_SYSTEM_BASE_URL = ""
MICROSERVICE_SYSTEM_BASE_URL = "http://127.0.0.1:8000/services/"

LOGO_SOURCE = os.getenv("LOGO_SOURCE")
