# Generated by Django 3.0.10 on 2023-12-05 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_green_rating', models.FloatField(default=0)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(max_length=150)),
                ('website', models.CharField(blank=True, max_length=150)),
                ('primary_email', models.EmailField(max_length=254)),
                ('is_vendor_green', models.BooleanField()),
                ('vendor_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_vendor.VendorDepartments')),
                ('vendor_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_vendor.VendorTasks')),
            ],
        ),
    ]
