# Generated by Django 3.0.10 on 2023-10-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequestmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
