# Generated by Django 3.0.10 on 2023-11-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_maintenancerequestmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettypechecks',
            name='anchoring_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettypechecks',
            name='communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettypechecks',
            name='electrical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettypechecks',
            name='engine_and_all_mechanical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettypechecks',
            name='fuel_systems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettypechecks',
            name='lifesaving_equipments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettypechecks',
            name='navigation_and_strobe_lights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettypechecks',
            name='steering_and_hydraulics',
            field=models.BooleanField(default=False),
        ),
    ]
