# Generated by Django 3.0.10 on 2023-11-24 02:45

# note; this actually covers changes which were already applied
# migrated with --fake in order to apply 0005, which was genuinely new

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231113_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentreModel',
            fields=[
                ('cost_centre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CostCentreModel'),
        ),
    ]
