# Generated by Django 3.0.10 on 2023-11-24 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231124_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaileduser',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CostCentreModel'),
        ),
    ]
