# Generated by Django 3.0.10 on 2023-11-24 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_detaileduser_cost_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequestmodel',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.CostCentreModel'),
        ),
    ]
