# Generated by Django 3.0.10 on 2023-11-24 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assetrequestmodel_cost_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('engine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hours', models.FloatField(default=-1, max_length=50)),
                ('VIN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.AssetModel')),
            ],
        ),
    ]
