# Generated by Django 3.0.10 on 2023-12-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assetrequestmodel_cost_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('received', 'received'), ('shortlisted', 'shortlisted'), ('denied', 'denied')], default='pending', max_length=50)),
                ('vendor_quote_id', models.CharField(max_length=50, null=True)),
                ('estimated_cost', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_quote_approved_by', to='api.DetailedUser')),
                ('asset_request', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_request_quote', to='api.AssetRequestModel')),
                ('disposal_request', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_quote', to='api.AssetDisposalModel')),
                ('maintenance_request', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_quote', to='api.MaintenanceRequestModel')),
                ('repair_request', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_quote', to='api.RepairsModel')),
                ('transfer_request', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_quote', to='api.AssetTransfer')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ApprovedVendorsModel')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, null=True, unique=True)),
                ('custom_id', models.CharField(max_length=255, null=True, unique=True)),
                ('inventory_type', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('per_unit_cost', models.FloatField(null=True)),
                ('date_of_manufacture', models.DateField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_created_by', to='api.DetailedUser')),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EquipmentTypeModel')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.LocationModel')),
                ('modified_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_modified_by', to='api.DetailedUser')),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequestFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(default='NA', max_length=150)),
                ('file_purpose', models.CharField(choices=[('other', 'other'), ('invoice', 'invoice'), ('quote', 'quote')], max_length=50)),
                ('file_name', models.TextField(default='NA', max_length=10000)),
                ('file_url', models.TextField(default='NA', max_length=10000)),
                ('bytes', models.BigIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('asset_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.AssetRequestModel')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_request_file_created_by', to='api.DetailedUser')),
                ('vendor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_request_file_vendor', to='api.ApprovedVendorsModel')),
            ],
        ),
    ]
