# Generated by Django 3.0.10 on 2023-12-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_enginemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineHistoryModel',
            fields=[
                ('engine_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_name', models.CharField(max_length=100)),
                ('updated_hours', models.FloatField(default=-1, max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.DetailedUser')),
            ],
        ),
    ]
