# Generated by Django 3.0.10 on 2023-12-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_enginehistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginehistorymodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
