# Generated by Django 3.0.10 on 2023-12-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_enginehistorymodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginehistorymodel',
            name='engine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EngineModel'),
        ),
        migrations.AlterField(
            model_name='enginehistorymodel',
            name='updated_hours',
            field=models.FloatField(default=-1, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enginehistorymodel',
            name='updated_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
