# Generated by Django 3.0.10 on 2023-12-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20231204_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginehistorymodel',
            name='responsible_daily_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.AssetDailyChecksModel'),
        ),
    ]
