# Generated by Django 3.0.10 on 2023-12-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_enginehistorymodel_responsible_daily_check'),
        ('api', '0007_assetrequestfile_inventory_requestquote'),
    ]

    operations = [
    ]
