# Generated by Django 3.0.10 on 2023-12-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20231205_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceforecastrules',
            name='linked_engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EngineModel'),
        ),
        migrations.AddField(
            model_name='maintenanceforecastruleshistory',
            name='linked_engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EngineModel'),
        ),
    ]
