# Generated by Django 3.0.10 on 2023-12-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20231205_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTableLayoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DetailedUser')),
            ],
        ),
    ]
