# Generated by Django 3.0.10 on 2024-01-16 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_usertablelayoutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCostCheck',
            fields=[
                ('fuel_cost_check_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('type', 'validate fuel types match'), ('volume_units', 'validate fuel volume units match'), ('volume_ratio', 'validate fuel volume relative to tank capacity (configurable threshold)'), ('cost_ratio', 'validate fuel cost per unit (configurable threshold)')], max_length=20)),
                ('volume_ratio_threshold', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Company')),
            ],
        ),
    ]
