# Generated by Django 3.0.10 on 2024-01-16 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_fuelcostcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcostcheck',
            name='cost_ratio_threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fuelcostcheck',
            name='cost_ratio_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FuelType'),
        ),
        migrations.AddField(
            model_name='fuelcostcheck',
            name='cost_ratio_units',
            field=models.CharField(choices=[('liter', 'liter'), ('gallon', 'gallon'), ('kg', 'kg'), ('lb', 'lb'), ('kWh', 'kWh'), ('SCM', 'SCM'), ('SCF', 'SCF')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcostcheck',
            name='type',
            field=models.CharField(choices=[('type', 'Validate that fuel types of cost record and asset are equal.'), ('volume_units', 'Validate that fuel volume units of cost record and asset are equal.'), ('volume_ratio', 'Validate that fuel volume of cost record relative to fuel tank capacity of asset is below a configurable ratio.'), ('cost_ratio', 'Validate that cost per unit of fuel is below a configurable threshold.')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelcostcheck',
            name='volume_ratio_threshold',
            field=models.FloatField(default=0),
        ),
    ]
