# Generated by Django 3.0.10 on 2024-01-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20240116_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifesaving_ok', models.BooleanField()),
                ('lifesaving_notes', models.TextField()),
                ('engine_ok', models.BooleanField()),
                ('engine_notes', models.TextField()),
                ('communications_ok', models.BooleanField()),
                ('communications_notes', models.TextField()),
                ('bilge_pump_ok', models.BooleanField()),
                ('bilge_pump_notes', models.TextField()),
                ('steering_controls_ok', models.BooleanField()),
                ('steering_controls_notes', models.TextField()),
                ('hatches_ok', models.BooleanField()),
                ('hatches_notes', models.TextField()),
                ('emergency_drills_ok', models.BooleanField()),
                ('emergency_drills_notes', models.TextField()),
                ('fire_extinguishers_ok', models.BooleanField()),
                ('fire_extinguishers_notes', models.TextField()),
                ('hull_ok', models.BooleanField()),
                ('hull_notes', models.TextField()),
                ('electrical_ok', models.BooleanField()),
                ('electrical_notes', models.TextField()),
                ('lights_ok', models.BooleanField()),
                ('lights_notes', models.TextField()),
                ('fuel_systems_ok', models.BooleanField()),
                ('fuel_systems_notes', models.TextField()),
                ('anchoring_ok', models.BooleanField()),
                ('anchoring_notes', models.TextField()),
                ('guard_rails_lines_ok', models.BooleanField()),
                ('guard_rails_lines_notes', models.TextField()),
                ('crew_qualifications_ok', models.BooleanField()),
                ('crew_qualifications_notes', models.TextField()),
                ('signature_name', models.CharField(max_length=100, null=True)),
                ('signature_date', models.CharField(max_length=100, null=True)),
                ('VIN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.AssetModel')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.AssetFile')),
            ],
        ),
    ]
