# Generated by Django 3.0.10 on 2024-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_annualreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcost',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='anchoring_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='bilge_pump_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='communications_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='crew_qualifications_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='electrical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='emergency_drills_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='engine_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='fire_extinguishers_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='fuel_systems_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='guard_rails_lines_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='hatches_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='hull_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='lifesaving_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='lights_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='steering_controls_notes',
            field=models.TextField(blank=True),
        ),
    ]
