# Generated by Django 3.0.10 on 2024-01-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20231211_2156'),
        ('api', '0017_auto_20240118_1511'),
    ]

    operations = [
    ]
