# Generated by Django 3.0.10 on 2024-01-18 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20240118_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='lifespan_years',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
