# Generated by Django 3.0.10 on 2024-03-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_assetmodel_lifespan_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdailychecksmodel',
            name='anchoring_system',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assetdailychecksmodel',
            name='communication',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assetdailychecksmodel',
            name='electrical',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assetdailychecksmodel',
            name='engine_and_all_mechanical',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assetdailychecksmodel',
            name='fuel_systems',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assetdailychecksmodel',
            name='lifesaving_equipments',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assetdailychecksmodel',
            name='navigation_and_strobe_lights',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assetdailychecksmodel',
            name='steering_and_hydraulics',
            field=models.BooleanField(null=True),
        ),
    ]
