# Generated by Django 3.0.10 on 2024-04-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20240314_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginehistorymodel',
            name='responsible_maintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.MaintenanceRequestModel'),
        ),
        migrations.AddField(
            model_name='enginehistorymodel',
            name='responsible_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.RepairsModel'),
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='daily_average_hours',
            field=models.FloatField(default=0),
        ),
    ]
