# Generated by Django 3.0.10 on 2025-10-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20240403_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdisposalmodel',
            old_name='primary_vendor_email',
            new_name='vendor_email',
        ),
        migrations.AlterField(
            model_name='assetdisposalmodel',
            name='replacement_reason',
            field=models.CharField(choices=[('end of useful life', 'end of useful life'), ('accident', 'accident'), ('equipment failure', 'equipment failure'), ('not applicable', 'not applicable'), ('incident', 'incident')], default='not applicable', max_length=50),
        ),
    ]
