# Generated by Django 3.0.10 on 2023-12-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('needs_reset', models.BooleanField(default=False)),
                ('is_uat', models.BooleanField(default=False)),
                ('upload_complete', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_db_access', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('NA', 'NA'), ('client', 'client'), ('vendor', 'vendor')], default='NA', max_length=255)),
            ],
        ),
    ]
