from django.db import models

class SnapshotDailyAsset(models.Model): 

    VIN = models.CharField(max_length=100, null=True, blank=True)
    parent = models.CharField(max_length=100, null=True, blank=True)
    equipment_type = models.CharField(max_length=100, null=True, blank=True)
    company = models.CharField(max_length=100, null=True, blank=True)
    jde_department = models.CharField(max_length=100, null=True, blank=True)
    original_location = models.CharField(max_length=100, null=True, blank=True)
    current_location = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    aircraft_compatability = models.CharField(max_length=100, null=True, blank=True)
    unit_number = models.CharField(max_length=100, null=True, blank=True)
    license_plate = models.CharField(max_length=100, null=True, blank=True)
    date_of_manufacture = models.DateField(null=True)
    department = models.CharField(max_length=100, null=True, blank=True)
    job_specification = models.CharField(max_length=100, null=True, blank=True)
    fire_extinguisher_quantity = models.CharField(max_length=100, null=True, blank=True)
    fire_extinguisher_inspection_date = models.DateField(null=True)
    path = models.CharField(max_length=300, null=True, blank=True)
    last_process = models.CharField(max_length=50, null=True, blank=True)
    hours_or_mileage = models.CharField(max_length=50, null=True, blank=True)
    mileage = models.FloatField(max_length=50, default=-1)
    hours = models.FloatField(max_length=50, default=-1)
    mileage_unit = models.CharField(max_length=50, null=True, blank=True)
    date_in_service = models.DateField(null=True)
    total_cost = models.FloatField(default=0)
    currency = models.CharField(max_length=100, null=True, blank=True)
    daily_average_hours = models.FloatField(default=0)
    daily_average_mileage = models.FloatField(default=0)
    replacement_hours = models.FloatField(null=True, default=0)
    replacement_mileage = models.FloatField(null=True, default=0)
    insurance_renewal_date = models.DateField(blank=True, null=True)
    registration_renewal_date = models.DateField(blank=True, null=True)
    load_capacity = models.FloatField(blank=True, null=True)
    load_capacity_unit = models.CharField(max_length=50, null=True, blank=True)
    fuel = models.CharField(max_length=100, null=True, blank=True)
    engine = models.CharField(max_length=50, null=True, blank=True)
    colour = models.CharField(max_length=50, default="NA")
    fuel_tank_capacity = models.FloatField(null=True)
    fuel_tank_capacity_unit = models.CharField(null=True, max_length=50)
    is_rental = models.BooleanField(null=True)
    monthly_subscription_cost = models.FloatField(null=True)

    date_created = models.DateTimeField(auto_now_add=True)