from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from .AssetIssue import IssueView
from .AssetOperationalCheck import DailyOperationalView
from .AssetRequest import AssetRequestView
from .BusinessUnit import BusinessUnitView
from .ApprovedVendors import ApprovedVendorsView
from .AssetDisposal import AssetDisposalView
from .Accidents import AccidentsView
from .Repairs import RepairsView
from .Maintenance import MaintenanceView
from .Locations import LocationView
from .Assets import AssetsView
from .Chart import ChartView
from .FleetGuru import FleetGuruView
from .Approvals import ApprovalsView
from .Transfer import TransferView
from .ErrorReport import ErrorReportView
from .AssetLog import AssetLogView
from .EquipmentType import EquipmentTypeView
from .Upload import UploadView
from .Test import TestView
from .WebJobs import WebJobsView
from .Cost import CostView
from .Notifications import NotificationsView
from .DailyInspection import DailyInspectionView
from .RequestQuote import RequestQuoteView
from .Inventory import InventoryView
from .CostCentre import CostCentreView
from .Engine import EngineView
from .UserTableLayout import UserTableLayoutView

urlpatterns = [
    path('Test', TestView.TestView.as_view()),
    path('Test/Form', TestView.TestFormView.as_view()),
    path('Test/Server/Connection', TestView.TestServerConnection.as_view()),
    path('Test/Server/Status/<int:status_code>', TestView.TestServerStatus.as_view()),
    path('Test/Server/Load', TestView.LoadTest.as_view()),
    path('Test/Server/Async/Load', TestView.LoadTestAsync.as_view()),
    path('Test/Server/Gateway/Interface', TestView.ServerGatewayInterface.as_view()),
    path('Test/Microservice/Connection', TestView.TestMicroserviceConnection.as_view()),
    path('Chart/Get/Operational/Cost', ChartView.GetOperationalCost.as_view()),
    path('Chart/Get/LifeCycle/Count/Type', ChartView.GetLifeCycleCountPerType.as_view()),
    path('Chart/Get/LifeCycle/Count', ChartView.GetLifeCycleCount.as_view()),
    path('Chart/Get/Status/Breakdown', ChartView.GetAssetStatusBreakdown.as_view()),
    path('Chart/Get/Process/Breakdown', ChartView.GetAssetProcessBreakdown.as_view()),
    path('Chart/Get/Location/Count/Operators/Assets', ChartView.GetAssetsAndOperatorsCountPerLocation.as_view()),
    path('Chart/Get/Asset/Performance/Leaderboard', ChartView.GetAssetPerformanceLeaderboard.as_view()),
    path('Chart/Get/Location/AssetTypes', ChartView.GetLocationAssetTypes.as_view()),
    path('Chart/Get/Location/Maintenance/Downtime/Average', ChartView.GetLocationMaintenanceDowntimeAverage.as_view()),
    path('Chart/Get/AssetChartParams', ChartView.GetAssetChartParams.as_view()),
    path('Chart/Get/RepairChartParams', ChartView.GetRepairsChartParams.as_view()),
    path('Chart/Get/AccidentChartParams', ChartView.GetAccidentChartParams.as_view()),
    path('Chart/Get/MaintenanceChartParams', ChartView.GetMaintenanceChartParams.as_view()),
    path('Chart/Get/Fuel/Usage/<str:_unit>', ChartView.GetFuelUsage.as_view()),
    path('Chart/Get/Fuel/Cost/<str:_time_unit>', ChartView.GetFuelCost.as_view()),
    path('Chart/Fleet/Usage', ChartView.GetFleetUsage.as_view()),
    path('Chart/Get/Fuel/Volume' , ChartView.GetFuelUsageVolume.as_view()),
    path('Chart/Get/dailyChecksAndAssets' , ChartView.GetdailyChecksAndAssets.as_view()),
    path('Chart/Get/ProcessCostByLocation' , ChartView.GetProcessCostByLocation.as_view()),
    path('Chart/Get/WorkOrderCompletionTime' , ChartView.GetWorkOrderCompletionTime.as_view()),
    path("Inventory/Add", InventoryView.AddInventory.as_view()),
    path("Inventory/Update", InventoryView.UpdateInventory.as_view()),
    path("Inventory/List", InventoryView.ListInventory.as_view()),
    path("Inventory/Get/<str:inventory_id>", InventoryView.GetInventoryByID.as_view()),
    path('Upload/Currency/<str:db_access>', UploadView.UploadCurrencyCSV.as_view()),
    path('Upload/Company/<str:db_access>', UploadView.UploadCompanyCSV.as_view()),
    path('Upload/RolePermissions/<str:db_access>', UploadView.UploadRolePermissionsCSV.as_view()),
    path('Upload/Assets', UploadView.UploadAssetCSV.as_view()),
    path('Upload/Locations', UploadView.UploadLocationCSV.as_view()),
    path('Upload/AssetTypes', UploadView.UploadAssetTypeCSV.as_view()),
    path('Upload/AssetTypeChecks', UploadView.UploadAssetTypeChecksCSV.as_view()),
    path('Upload/FuelTypes', UploadView.UploadFuelTypeCSV.as_view()),
    path('Upload/BusinessUnits', UploadView.UploadBusinessUnitCSV.as_view()),
    path('Upload/JobSpecifications', UploadView.UploadJobSpecificationCSV.as_view()),
    path('Upload/Manufacturers', UploadView.UploadManufacturerCSV.as_view()),
    path('Upload/ManufacturersAssetTypes', UploadView.UploadManufacturerAssetTypeCSV.as_view()),
    path('Upload/EquipmentTypes', UploadView.UploadEquipmentTypeCSV.as_view()),
    path('Upload/AssetRequestJustifications', UploadView.UploadAssetRequestJustificationCSV.as_view()),
    path('Upload/Users', UploadView.UploadUserCSV.as_view()),
    path('Upload/UserLocations', UploadView.UploadUserLocationCSV.as_view()),
    path('Upload/InspectionTypes', UploadView.UploadInspectionTypeCSV.as_view()),
    path('Upload/ApprovedVendors', UploadView.UploadApprovedVendorCSV.as_view()),
    path('Upload/Maintenance/Rules', UploadView.UploadMaintenanceRuleCSV.as_view()),
    path('Upload/Maintenance', UploadView.UploadMaintenanceCSV.as_view()),
    path('Upload/Maintenance/Request', UploadView.UploadMaintenanceCSV.as_view()),
    path('Assets/Add', AssetsView.AddAsset.as_view()),
    path('Assets/Add/Bulk', AssetsView.AddBulkAsset.as_view()),
    path('Assets/Add/CustomField/<str:vin>', AssetsView.UpdateAssetCustomFilter.as_view()),
    path('Assets/Delete/CustomField/<str:vin>', AssetsView.DeleteAssetCustomFilter.as_view()),
    path('Assets/VINs', AssetsView.GetAllAssetVINs.as_view()),
    path('Assets/VIN/<str:pk>', AssetsView.SearchByFullVINView.as_view()),
    path('Assets/All', AssetsView.GetAllAssets.as_view()),
    path('Assets/AverageMaintenanceCost', AssetsView.GetAverageMaintenanceCost.as_view()),
    path('Assets/AverageMaintenanceCostPerUnit/<str:start_date>:<str:end_date>', AssetsView.GetAverageMaintenanceCostPerUnit.as_view()),
    path('Assets/AverageCostPerUnit/<str:start_date>:<str:end_date>', AssetsView.GetAverageCostPerUnit.as_view()),
    path('AssetsByLast/VIN/UnitNumber/<str:substring>', AssetsView.SearchByVINAndUnitNumber.as_view()),
    path('Assets/Add/Warranty/<str:vin>', AssetsView.AddWarrantyFiles.as_view()),
    path('Assets/Add/Insurance/<str:vin>', AssetsView.AddInsuranceFiles.as_view()),
    path('Assets/Add/AnnualReport/<str:vin>', AssetsView.PostAnnualReport.as_view()),
    path('Assets/Get/AnnualReport/<str:vin>', AssetsView.GetAnnualReport.as_view()),
    path('Assets/Get/AnnualReport/KPI/Data/<str:year>', AssetsView.GetAnnualReportKPI.as_view()),
    path('Assets/Get/LifeCycle/KPI/DisposalSchedule', AssetsView.GetLifeCycleDisposalScheduleKPI.as_view()),
    path('Assets/Add/Registration/<str:vin>', AssetsView.AddRegistrationFiles.as_view()),
    path('Assets/Add/Other/<str:vin>', AssetsView.AddOtherFiles.as_view()),
    path('Assets/Add/Support/Files/<str:vin>', AssetsView.AddSupportingFiles.as_view()),
    path('Assets/Get/Files/<str:vin>', AssetsView.GetAssetFiles.as_view()),
    path('Assets/Get/Files/LatestUploads/<str:vin>', AssetsView.GetAllInsAndRegFiles.as_view()),
    path('Assets/Get/Downtime/<str:vin>', AssetsView.GetAssetDowntime.as_view()),
    path('Assets/Get/AverageDowntime/<str:start_date>:<str:end_date>', AssetsView.GetAssetDowntimeDaterange.as_view()),
    path('Assets/Get/Fleet/Downtime', AssetsView.GetFleetDowntime.as_view()),
    path('Assets/Get/Usage/Tracking/Types', AssetsView.GetUsageTrackingTypes.as_view()),
    path('Assets/Validate/Usage', AssetsView.IsUsageValid.as_view()),
    path('Assets/Get/Checks/<str:vin>', AssetsView.GetAssetChecks.as_view()),
    path('Assets/Update', AssetsView.UpdateAsset.as_view()),
    path('Assets/Reassign', AssetsView.ReassignAsset.as_view()),
    path('Assets/Set/Parent', AssetsView.SetAssetParent.as_view()),
    path('Assets/Add/Children', AssetsView.AddAssetChildren.as_view()),
    path('Assets/Remove/Parent', AssetsView.RemoveAssetParent.as_view()),
    path('Assets/Remove/Children', AssetsView.RemoveAssetChildren.as_view()),
    path('Assets/Get/Children/<str:vin>', AssetsView.GetAssetChildren.as_view()),
    path('Assets/Get/MeanTimeBetweenFailure/<str:start_date>:<str:end_date>', AssetsView.GetMeanTimeBetweenFailure.as_view()),
    path('Assets/Get/End/Lifecycle', AssetsView.GetUpcommingEndOfLife.as_view()), 
    path('Assets/Set/Status', AssetsView.SetAssetStatus.as_view()),
    path('Issues/VIN/<str:vin>', IssueView.SearchIssueByVIN.as_view()),
    path('Issues/Add', IssueView.AddIssue.as_view()),
    path('Issues/Update', IssueView.UpdateIssue.as_view()),
    path('Issue/Complete/ID/<str:_issue_id>/Status/<str:_status>', IssueView.MarkIssueStatus.as_view()),
    path('Issues/Set/Type', IssueView.SetIssueType.as_view()),
    path('Issues/Get/Repair/ID/<str:_repair_id>', IssueView.GetIssueByRepairID.as_view()),
    path('Issues/List/Type', IssueView.ListFilteredIssues.as_view()),
    path('Issues/List', IssueView.GetIssuesList.as_view()),
    path('Issues/Count/Critical', IssueView.GetCriticalIssueCount.as_view()),
    path('Issues/Count/Non-Critical', IssueView.GetNonCriticalIssueCount.as_view()),
    path('Issues/Count/Unresolved', IssueView.GetUnresolvedIssueCount.as_view()),
    path('Issues/Count/Resolved', IssueView.GetResolvedIssueCount.as_view()),
    path('Issues/Percentage/Resolved', IssueView.GetIssuePercentageResolved.as_view()),
    path('Issues/ID/<str:_issue_id>/Set/Accident/ID/<str:_accident_id>', IssueView.SetIssueAccidentID.as_view()),
    path('Issues/Get/Unresolved/<str:_asset_VIN>', IssueView.GetUnresolvedIssuesByVIN.as_view()),
    path('Issues/Get/Details/ID/<str:issue_id>', IssueView.GetIssueDetailsByID.as_view()),
    path('Issues/Get/Details/CustomID/<str:custom_issue_id>', IssueView.GetIssueDetailsByCustomID.as_view()),
    path('DailyOperationalChecks/Add', DailyOperationalView.AddDailyOperationalCheckByVIN.as_view()),
    path('DailyOperationalChecks/Update', DailyOperationalView.UpdateDailyOperatorCheck.as_view()),
    path('DailyOperationalChecks/VIN/<str:vin>', DailyOperationalView.GetDailyOperationalChecksByVINView.as_view()),
    path('DailyOperationalChecks/Get/Details/ID/<str:op_check_id>', DailyOperationalView.GetDailyOperationalCheckDetailsByID.as_view()),
    path('DailyOperationalChecks/Get/Details/CustomID/<str:custom_op_check_id>', DailyOperationalView.GetDailyOperationalCheckDetailsByCustomID.as_view()),
    path('DailyOperationalChecks/noDailyCheck',DailyOperationalView.GetAllAssetsWithNoDailyCheck.as_view()),
    path('AssetType/List', AssetRequestView.GetAssetTypes.as_view()),
    path('AssetType/<int:asset_id>/Manufacturers', AssetRequestView.GetManufacturerByAssetType.as_view()),
    path('AssetType/<int:asset_id>/Manufacturer/<int:manufacturer_id>/Equipments', AssetRequestView.GetEquipment.as_view()),
    path('BusinessUnit/List', BusinessUnitView.GetBusinessUnits.as_view()),
    path('CostCentre/List',CostCentreView.GetAll.as_view()),
    path('AssetRequest/Justifications', AssetRequestView.GetJustifications.as_view()),
    path('AssetRequest/Add', AssetRequestView.AddAssetRequest.as_view()),
    path('AssetRequest/Update', AssetRequestView.UpdateAssetRequest.as_view()),
    path('AssetRequest/Update/Status', AssetRequestView.UpdateAssetRequestStatus.as_view()),
    path('AssetRequest/InProgress/List', AssetRequestView.ListInProgressAssetRequests.as_view()),
    path('AssetRequest/Delivered/List', AssetRequestView.ListDeliveredAssetRequests.as_view()),
    path('AssetRequest/Get/Details/ID/<str:asset_request_id>', AssetRequestView.GetAssetRequestDetailsByID.as_view()),
    path('AssetRequest/Get/Details/CustomID/<str:asset_request_custom_id>', AssetRequestView.GetAssetRequestDetailsByCustomID.as_view()),
    path('ApprovedVendor/Departments', ApprovedVendorsView.GetDepartments.as_view()),
    path('ApprovedVendor/Tasks', ApprovedVendorsView.GetTasks.as_view()),
    path('ApprovedVendor/List/By/Department/<int:_dep_id>', ApprovedVendorsView.GetVendorsByDepartment.as_view()),
    path('ApprovedVendor/List/By/Task/<str:_task_id>', ApprovedVendorsView.GetVendorsByTask.as_view()),
    path('ApprovedVendor/By/Department/<int:_dep_id>/By/Task/<int:_task_id>', ApprovedVendorsView.GetApprovedVendorByTaskAndDepartment.as_view()),
    path('ApprovedVendor/List/All', ApprovedVendorsView.GetAllVendors.as_view()),
    path('AssetDisposal/Get/Tradein/NoAssetRequest', AssetDisposalView.GetAssetDisposalTradeinNoAssetRequest.as_view()),
    path('AssetDisposal/Add/CompanyDirectedSale', AssetDisposalView.AddCompanyDirectedSaleDisposal.as_view()),
    path('AssetDisposal/Add/Auction', AssetDisposalView.AddAuctionDisposal.as_view()),
    path('AssetDisposal/Add/Repurpose', AssetDisposalView.AddRepurposeDisposal.as_view()),
    path('AssetDisposal/Add/Scrap', AssetDisposalView.AddScrapDisposal.as_view()),
    path('AssetDisposal/Add/Donation', AssetDisposalView.AddDonationDisposal.as_view()),
    path('AssetDisposal/Add/TradeIn', AssetDisposalView.AddTradeInDisposal.as_view()),
    path('AssetDisposal/Add/Transfer', AssetDisposalView.AddTransferDisposal.as_view()),
    path('AssetDisposal/Add/WriteOff', AssetDisposalView.AddWriteOffDisposal.as_view()),
    path('AssetDisposal/Update', AssetDisposalView.UpdateDisposal.as_view()),
    path('AssetDisposal/Update/Status/CompanyDirectedSale', AssetDisposalView.UpdateCompanyDirectedSaleDisposalStatus.as_view()),
    path('AssetDisposal/Update/Status/Auction', AssetDisposalView.UpdateAuctionDisposalStatus.as_view()),
    path('AssetDisposal/Update/Status/Repurpose', AssetDisposalView.UpdateRepurposeDisposalStatus.as_view()),
    path('AssetDisposal/Update/Status/Scrap', AssetDisposalView.UpdateScrapDisposalStatus.as_view()),
    path('AssetDisposal/Update/Status/Donation', AssetDisposalView.UpdateDonationDisposalStatus.as_view()),
    path('AssetDisposal/Update/Status/TradeIn', AssetDisposalView.UpdateTradeInDisposalStatus.as_view()),
    path('AssetDisposal/Update/Status/Transfer', AssetDisposalView.UpdateTransferDisposalStatus.as_view()),
    path('AssetDisposal/Update/Status/WriteOff', AssetDisposalView.UpdateWriteOffDisposalStatus.as_view()),
    path('AssetDisposal/List', AssetDisposalView.GetAssetDisposals.as_view()),
    path('AssetDisposal/Get/Details/ID/<str:disposal_id>', AssetDisposalView.GetAssetDisposalDetailsByID.as_view()),
    path('AssetDisposal/Get/Details/CustomID/<str:custom_disposal_id>', AssetDisposalView.GetAssetDisposalDetailsByCustomID.as_view()),
    path('AssetDisposal/Get/Writeoff/NoAccident', AssetDisposalView.GetAssetDisposalWriteOffNoAccident.as_view()),
    path('Accident/Add', AccidentsView.AddAccident.as_view()),
    path('Accident/Update', AccidentsView.UpdateAccident.as_view()),
    path('Accident/VIN/<str:_vin>', AccidentsView.GetAccidentsByVIN.as_view()),
    path('Accident/Get/Details/ID/<str:accident_id>', AccidentsView.GetAccidentDetailsByID.as_view()),
    path('Accident/Get/Details/CustomID/<str:custom_accident_id>', AccidentsView.GetAccidentDetailsByCustomID.as_view()),
    path('Accident/List/Date', AccidentsView.ListAccidentByDate.as_view()),
    path('Accident/List', AccidentsView.GetAccidentList.as_view()),
    path('Accident/Notification/Sent', AccidentsView.SetNotificationStatus.as_view()),
    path('Accident/Report/Completed', AccidentsView.SetAccidentReportStatus.as_view()),
    path('Accident/Set/Resolved/<str:accident_id>', AccidentsView.MarkAccidentStatusToResolved.as_view()),
    path('Accident/Count/Unresolved', AccidentsView.GetAccidentCountUnresolved.as_view()),
    path('Accident/Count/Resolved', AccidentsView.GetAccidentCountResolved.as_view()),
    path('Accident/Average/<str:start_date>:<str:end_date>', AccidentsView.GetAverageAccidentCount.as_view()),
    path('Accident/Percentage/Resolved', AccidentsView.GetAccidentPercentageResolved.as_view()),
    path('Accident/Downtime/Asset/<str:_vin>', AccidentsView.GetAccidentDowntimeForAsset.as_view()),
    path('Accident/Downtime/Fleet', AccidentsView.GetAccidentDowntimeForFleet.as_view()),
    path('Repair/Add', RepairsView.AddRepairs.as_view()),
    path('Repair/Update', RepairsView.UpdateRepair.as_view()),
    path('Repair/Update/Status', RepairsView.UpdateRepairStatus.as_view()),
    path('Repair/List', RepairsView.ListRepairs.as_view()),
    path('Repair/Complete/List', RepairsView.ListCompleteRepairs.as_view()),
    path('Repair/Vendor/Update', RepairsView.AddVendor.as_view()),
    path('Repair/VIN/<str:_vin>', RepairsView.GetRepairsByVIN.as_view()),
    path('Repair/Count/Unresolved', RepairsView.GetRepairCountUnresolved.as_view()),
    path('Repair/Count/Resolved', RepairsView.GetRepairCountResolved.as_view()),
    path('Repair/Percentage/Resolved', RepairsView.GetRepairPercentageResolved.as_view()),
    path('Repair/Replacement/Suggestions/<str:_vin>', RepairsView.GetReplacemenetSuggestions.as_view()),
    path('Repair/Get/Details/ID/<str:repair_id>', RepairsView.GetRepairDetailByID.as_view()),
    path('Repair/Get/Details/WorkOrder/<str:work_order>', RepairsView.GetRepairDetailByWorkOrder.as_view()),
    path('Repair/Add/Files/<int:repair_id>', RepairsView.AddRepairFiles.as_view()),
    path('Maintenance/Add/Batch', MaintenanceView.AddBatchMaintenanceRequest.as_view()),
    path('Maintenance/Add/Files/<str:maintenance_id>', MaintenanceView.AddMaintenanceFiles.as_view()),
    path('Maintenance/Update', MaintenanceView.UpdateMaintenance.as_view()),    
    path('Maintenance/Update/Status', MaintenanceView.UpdateMaintenanceStatus.as_view()),
    path('Maintenance/List', MaintenanceView.ListMaintenance.as_view()),
    path('Maintenance/Completed/List', MaintenanceView.ListCompletedMaintenance.as_view()),
    path('Maintenance/Inspection/List', MaintenanceView.ListInspections.as_view()),
    path('Maintenance/VIN/<str:_vin>', MaintenanceView.GetMaintenanceByVIN.as_view()),
    path('Maintenance/Get/Details/ID/<str:maintenance_id>', MaintenanceView.GetMaintenanceDetailsByID.as_view()),
    path('Maintenance/Get/Details/WorkOrder/<str:work_order>', MaintenanceView.GetMaintenanceDetailsByWorkOrder.as_view()),
    path('Maintenance/Update/<str:maintenance_id>', MaintenanceView.UpdateVendorAndEstimatedDeliveryDate.as_view()),
    path('Maintenance/Count/Incomplete', MaintenanceView.GetIncompleteMaintenanceRequestCount.as_view()),
    path('Maintenance/Count/Complete', MaintenanceView.GetCompleteMaintenanceRequestCount.as_view()),
    path('Maintenance/Percentage/Complete', MaintenanceView.GetMaintenanceRequestPercentageComplete.as_view()),
    path('Maintenance/Forecast/Rule/Add', MaintenanceView.AddMaintenanceForecastRule.as_view()),
    path('Maintenance/Forecast/Rule/List', MaintenanceView.GetMaintenanceForecastRules.as_view()),
    path('Maintenance/Forecast/Rule/List/VIN/<str:_vin>', MaintenanceView.GetMaintenanceForecastRulesByVIN.as_view()),
    path('Maintenance/Forecast/Rule/Details/ID/<str:maintenance_rule_id>', MaintenanceView.GetMaintenanceForecastRuleDetailByID.as_view()),
    path('Maintenance/Forecast/Rule/Details/CustomID/<str:custom_maintenance_rule_id>', MaintenanceView.GetMaintenanceForecastRuleDetailByCustomID.as_view()),
    path('Maintenance/Forecast/Rule/Daterange', MaintenanceView.GetMaintenanceForecastForRule.as_view()),
    path('Location/List', LocationView.ListLocations.as_view()),
    path('FleetGuru/<str:_process_name>', FleetGuruView.GetInformation.as_view()),
    path('Approval/Create', ApprovalsView.CreateApprovalRequest.as_view()),
    path('Approval/Set/Status', ApprovalsView.SetApprovalResult.as_view()),
    path('Approval/Get/Requested', ApprovalsView.GetRequestedApprovals.as_view()),
    path('Approval/Get/Approve', ApprovalsView.GetApproveApprovals.as_view()),
    path('Transfer/Create', TransferView.AddTransfer.as_view()),
    path('Transfer/Update', TransferView.UpdateTransfer.as_view()),
    path('Transfer/Update/Status', TransferView.UpdateTransferStatus.as_view()),
    path('Transfer/Get/User/Location', TransferView.GetTransfersForUserLocation.as_view()),
    path('Transfer/Get/User/Location/VIN/<str:_vin>', TransferView.GetTransfersForUserLocationByVIN.as_view()),
    path('Transfer/List', TransferView.GetAssetTransfersList.as_view()),
    path('Transfer/Get/Details/ID/<str:transfer_id>', TransferView.GetTransferDetailByID.as_view()),
    path('Transfer/Get/Details/CustomID/<str:custom_transfer_id>', TransferView.GetTransferDetailByCustomID.as_view()),
    path('Transfer/Add/Files/<int:transfer_id>', TransferView.AddTransferFiles.as_view()),
    path('ErrorReport/Create', ErrorReportView.CreateErrorReport.as_view()),
    path('Asset/Add/Comment', AssetLogView.AddAssetComment.as_view()),
    path('Asset/Get/Logs/Daterange', AssetLogView.GetLogsByVINForDateRange.as_view()),
    path('Asset/Get/Logs/<str:_vin>', AssetLogView.GetLogsByVIN.as_view()),
    path('Asset/Get/Logs/Event/Types', AssetLogView.GetEventTypes.as_view()),
    path('Asset/Get/JobSpecifications', AssetsView.ListJobSpecification.as_view()),
    path('Asset/Get/Utilization/<str:start_date>:<str:end_date>', ChartView.GetFleetUtilizationDatetime.as_view()),
    path('Asset/Get/Utilization/Percentage/<str:start_date>:<str:end_date>', ChartView.GetFleetUtilizationPercentageDatetime.as_view()),
    path('EquipmentType/Add', EquipmentTypeView.AddEquipmentType.as_view()),
    path('EquipmentType/Get/All', EquipmentTypeView.GetAllEquipmentTypes.as_view()),
    path('EquipmentType/Update', EquipmentTypeView.UpdateEquipmentType.as_view()),
    path('AssetType/List', AssetRequestView.GetAssetTypes.as_view()),
    path('AssetType/Update', AssetRequestView.UpdateAssetType.as_view()),
    path('AssetType/Add/CustomField/<str:asset_type_id>', AssetRequestView.AddAssetTypeCustomField.as_view()),
    path('AssetType/Delete/CustomField/<str:asset_type_id>', AssetRequestView.DeleteAssetTypeCustomField.as_view()),
    path('AssetType/List/With/Checks', EquipmentTypeView.GetAssetTypesWithChecks.as_view()),
    path('AssetType/List/Without/Checks', EquipmentTypeView.GetAssetTypesWithoutChecks.as_view()),
    path('AssetType/<int:asset_id>/Manufacturers', AssetRequestView.GetManufacturerByAssetType.as_view()),
    path('AssetType/<int:asset_id>/Manufacturer/<int:manufacturer_id>/Equipments', AssetRequestView.GetEquipment.as_view()),
    path('AssetType/Checks/Add', EquipmentTypeView.AddAssetTypeChecks.as_view()),
    path('AssetType/Checks/Update', EquipmentTypeView.UpdateAssetTypeChecks.as_view()),
    path('AssetType/Checks/List', EquipmentTypeView.GetAssetTypeChecks.as_view()),
    path('WebJobs/MaintenanceAndRepairSetAssetInop', WebJobsView.MaintenanceAndRepairSetAssetInop.as_view()),
    path('WebJobs/CreateFleetDailySnapshot', WebJobsView.CreateFleetDailySnapshot.as_view()), 
    path('WebJobs/CreateCostDailySnapshot', WebJobsView.CreateCostDailySnapshot.as_view()),
    path('WebJobs/CreateDailyCountsSnapshot', WebJobsView.CreateDailyCountsSnapshot.as_view()),
    path('WebJobs/NotifyMaintenance', WebJobsView.NotifyMaintenance.as_view()), 
    path('WebJobs/CreateDailyCurrencySnapshot', WebJobsView.CreateDailyCurrencySnapshot.as_view()),
    path('WebJobs/NotifyExpiry', WebJobsView.NotifyExpiry.as_view()), 
    path('Webjobs/ServiceBus/ReceiveMessages', WebJobsView.ReceiveMessages.as_view()),
    path('Fuel/Get/All/Orders', CostView.GetFuelOrders.as_view()),
    path('Fuel/Add/Cost', CostView.AddFuelCost.as_view()),
    path('Fuel/Update/Cost', CostView.UpdateFuelCost.as_view()),
    path('Fuel/Update/Flagged', CostView.UpdateFuelFlagged.as_view()),
    path('Fuel/Delete/Cost', CostView.DeleteFuelCost.as_view()),
    path('Fuel/Get/Costs/VIN/<str:_vin>', CostView.GetFuelCostByVIN.as_view()),
    path('Fuel/FuelCards/Get/BusinessUnit/<int:business_unit_id>', CostView.GetFuelCards.as_view()),
    path('Fuel/FuelCards/Add', CostView.AddFuelCard.as_view()),
    path('Fuel/FuelCards/Update', CostView.UpdateFuelCard.as_view()),
    path('License/Add/Cost', CostView.AddLicenseCost.as_view()),
    path('License/Delete/Cost', CostView.DeleteLicenseCost.as_view()),
    path('License/Get/All/Costs', CostView.GetLicenseCostList.as_view()),
    path('License/Get/Costs/VIN/<str:_vin>', CostView.GetLicenseCostByVIN.as_view()),
    path('Rental/Add/Cost', CostView.AddRentalCost.as_view()),
    path('Rental/Delete/Cost', CostView.DeleteRentalCost.as_view()),
    path('Rental/Get/All/Costs', CostView.GetRentalCostList.as_view()),
    path('Rental/Get/Costs/VIN/<str:_vin>', CostView.GetRentalCostByVIN.as_view()),
    path('Rental/Get/Costs/Accident/<str:accident_id>', CostView.GetRentalCostByAccidentID.as_view()),
    path('Rental/Get/Costs/Maintenance/<str:maintenance_id>', CostView.GetRentalCostByMaintenanceID.as_view()),
    path('Rental/Get/Costs/Repair/<str:repair_id>', CostView.GetRentalCostByRepairID.as_view()),
    path('Labor/Add/Cost', CostView.AddLaborCost.as_view()),
    path('Labor/Delete/Cost', CostView.DeleteLaborCost.as_view()),
    path('Labor/Get/All/Costs', CostView.GetLaborCostList.as_view()),
    path('Labor/Get/Costs/VIN/<str:_vin>', CostView.GetLaborCostByVIN.as_view()),
    path('Labor/Get/Costs/Maintenance/<str:maintenance_id>', CostView.GetLaborCostByMaintenanceID.as_view()),
    path('Labor/Get/Costs/Issue/<str:issue_id>', CostView.GetLaborCostByIssueID.as_view()),
    path('Labor/Get/Costs/Issues', CostView.GetLaborCostByIssueIDList.as_view()),
    path('Labor/Get/Costs/Disposal/<str:disposal_id>', CostView.GetLaborCostByDisposalID.as_view()),
    path('Labor/Update/Cost', CostView.UpdateLaborCost.as_view()),
    path('Insurance/Add/Cost', CostView.addInsuranceCost.as_view()),
    path('Insurance/Delete/Cost', CostView.DeleteInsuranceCost.as_view()),
    path('Insurance/Get/All/Costs', CostView.getInsuranceList.as_view()),
    path('Insurance/Get/Costs/Accident/<str:accident_id>', CostView.getInsuranceByAccidentID.as_view()),
    path('Insurance/Get/Costs/VIN/<str:_vin>', CostView.getInsuranceByVIN.as_view()),
    path('Acquisition/Add/Cost', CostView.AddAcquisitionCost.as_view()),
    path('Acquisition/Delete/Cost', CostView.DeleteAcquisitionCost.as_view()),
    path('Acquisition/Get/Costs/VIN/<str:_vin>', CostView.GetAcquisitionCostByVIN.as_view()),
    path('Acquisition/Get/All/Costs', CostView.GetAcquisitionCostList.as_view()),
    path('Delivery/Add/Cost', CostView.AddDeliveryCost.as_view()),
    path('Delivery/Delete/Cost', CostView.DeleteDeliveryCost.as_view()),
    path('Delivery/Get/Costs/Maintenance/<str:maintenance_id>', CostView.GetDeliveryCostByMaintenance.as_view()),
    path('Delivery/Get/Costs/Repair/<str:repair_id>', CostView.GetDeliveryCostByRepair.as_view()),
    path('Delivery/Get/Costs/AssetRequest/<str:asset_request_id>', CostView.GetDeliveryCostByAssetRequest.as_view()),
    path('Delivery/Get/Costs/Disposal/<str:disposal_id>', CostView.GetDeliveryCostByDisposalID.as_view()),
    path('Delivery/Get/Costs/VIN/<str:vin>', CostView.GetDeliveryCostByVIN.as_view()),
    path('Delivery/Get/All/Costs', CostView.GetDeliveryCostList.as_view()),
    path('Parts/Add/Cost', CostView.AddPartsCost.as_view()),
    path('Parts/Delete/Cost', CostView.DeletePartsCost.as_view()),
    path('Parts/Get/All/Costs', CostView.GetPartsCostList.as_view()),
    path('Parts/Get/Costs/Maintenance/<str:maintenance_id>', CostView.GetPartsCostByMaintenance.as_view()),
    path('Parts/Get/Costs/Issue/<str:issue_id>', CostView.GetPartsCostByIssue.as_view()),
    path('Parts/Get/Costs/Issues', CostView.GetPartsCostByIssueIDList.as_view()),
    path('Parts/Get/Costs/Disposal/<str:disposal_id>', CostView.GetPartsCostByDisposalID.as_view()),
    path('Parts/Get/Costs/Number/<str:number>', CostView.GetPartsCostByNumber.as_view()),
    path('Parts/Get/Costs/VIN/<str:_vin>', CostView.GetPartsCostByVIN.as_view()),
    path('Parts/Update/Cost', CostView.UpdatePartsCost.as_view()),
    path('Fuel/Get/All/FuelTypes', CostView.GetFuelTypes.as_view()),
    path('Fuel/Get/All/FuelCards', CostView.GetAllFuelCards.as_view()),
    path('Currency/Get/All/CurrencyTypes', CostView.GetCurrencyTypes.as_view()),
    path('Fuel/Get/All/VolumeUnits', CostView.GetVolumeUnitChoices.as_view()),
    path('Invoice/Get/Data/', CostView.GetInvoiceData.as_view()),
    path('Report/WorkOrder/Cost', CostView.ExportWorkOrderCosts.as_view()),
    path('Notifications/Config/List', NotificationsView.ListNotificationConfigs.as_view()),
    path('Notifications/Config/Edit', NotificationsView.EditNotificationConfigs.as_view()),
    path('DailyInspection/List', DailyInspectionView.GetAllDailyInspection.as_view()),
    path('DailyInspection/Get/VIN/<str:_vin>', DailyInspectionView.GetDailyInspectionsByVIN.as_view()),
    path('DailyInspection/Add/VIN/<str:_vin>', DailyInspectionView.AddDailyInspectionByVIN.as_view()),
    path('Engine/Add',EngineView.Add.as_view()),
    path('Engine/Remove',EngineView.Remove.as_view()),
    path('Engine/Update',EngineView.Update.as_view()),
    path('Engine/ID/<str:id>',EngineView.GetByID.as_view()),
    path('Engine/History/ID/<str:id>',EngineView.GetHistory.as_view()),
    path('Engine/VIN/<str:vin>',EngineView.GetByVIN.as_view()),
    path('Engine/History/VIN/<str:vin>',EngineView.GetHistoryByVIN.as_view()),
    path('TableLayout/Set',UserTableLayoutView.SetByKey.as_view()),
    path('TableLayout/Get',UserTableLayoutView.GetByKey.as_view()),
    path('TableLayout/All',UserTableLayoutView.GetAll.as_view()),
    path('TableLayout/Delete',UserTableLayoutView.DeleteByKey.as_view()),
    path('Fuel/Cost/Check/Get/All',CostView.SanityCheckGetAll.as_view()),
    path('Fuel/Cost/Check/Add',CostView.SanityCheckAdd.as_view()),
    path('Fuel/Cost/Check/Delete',CostView.SanityCheckDelete.as_view()),
    path('Fuel/Cost/Check/Types',CostView.SanityCheckGetTypes.as_view()),

    path('Analytics/', include('analytics.urls')),
    path('Vendor/', include('api_vendor.urls')),
    path('Payment/', include('payment.urls')),
    path('ghg/', include('api_ghg.urls')),
]

urlpatterns = format_suffix_patterns(urlpatterns)
